import React from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  useFonts,
  Figtree_400Regular,
  Figtree_500Medium,
  Figtree_600SemiBold,
  Figtree_700Bold,
} from "@expo-google-fonts/figtree";
// @ts-ignore -- generated by sb-rn-get-stories, not committed
import { view } from "./.ondevice/storybook.requires";

const StorybookUI = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

const StorybookUIRoot: React.FC = () => {
  const [fontsLoaded] = useFonts({
    Figtree_400Regular,
    Figtree_500Medium,
    Figtree_600SemiBold,
    Figtree_700Bold,
  });

  if (!fontsLoaded) return null;
  return <StorybookUI />;
};

export default StorybookUIRoot;
